resources:
- name: test1
  type: git
  source:
    uri: https://github.com/sandyg1/test1.git
    branch: master

jobs:
- name: variables
  plan:
  - aggregate:
    - get: test1
  - task: print-vars
    file: test1/pipeline/tasks/print-vars.yml
    params:
      ssh_private_key: ((id_rsa.private_key))
      ssh_public_key: ((id_rsa.public_key))
