
resources:
- name: test1
  type: git
  source:
    uri: {{github_url}}
    username: {{github_token}}

jobs:

- name: test-ssh
  plan:
  - aggregate:
    - get: test1
  - task: SSH-and-SCP
    file: test1/pcf-cfops-backup/pipeline-work/task.yml
    params:
      OPSMAN_IP: {{opsman_ip}}
      SSHPASS: {{opsman_ssh_password}}
      CERT: {{cert}}
      KEY: {{key}}
